In [11]:
import pandas as pd
import numpy as np

In [29]:
#convertendo um array pra uma série:
arr1=np.array([10,20,30])
serie1=pd.Series(arr1)
print(arr1)
print(serie1)

[10 20 30]
0    10
1    20
2    30
dtype: int64


In [30]:
#convertendo uma série pra um array:
arr2=serie1.to_numpy()
print(arr2)

[10 20 30]


**Dataframes e suas Principais Funções:**

In [31]:
#criação:
arr3=np.array([[1,2],[3,4]])
df_arr=pd.DataFrame(arr3,columns=['A','B'])
print (arr3)
print(df_arr)

[[1 2]
 [3 4]]
   A  B
0  1  2
1  3  4


In [32]:
#transformando uma coluna em uma série:
coluna_serie=df_arr['A']
print(coluna_serie)

0    1
1    3
Name: A, dtype: int64


In [33]:
#contagem de valores:
estados=pd.DataFrame({'cidade':['RJ','SP','MG','ES','RJ', 'RJ','SP']})
print(estados['cidade'].value_counts())

cidade
RJ    3
SP    2
MG    1
ES    1
Name: count, dtype: int64


In [35]:
#Cálculo Estatísticos:
notas=pd.DataFrame({'Notas':[10,8.5,7,7,7,7,5.6,6,8,8,7,10,4,9,8.5]})
print(notas['Notas'].sum())  #soma
print(notas['Notas'].mean())  #média
print(notas['Notas'].median())  #mediana
print(notas.describe()) #resumo das estatísticas

112.6
7.506666666666666
7.0
           Notas
count  15.000000
mean    7.506667
std     1.617081
min     4.000000
25%     7.000000
50%     7.000000
75%     8.500000
max    10.000000


In [37]:
array_original=np.arrange(1,13)
print(array_original)
array_3_por_4=array_original.reshape(3,4)
print(array_3_por_4)
print('------------')
#DESAFIO
array_4_por_3=array_3_por_4.tranpose()
print(array_4_por_3)
array_unidimensional=array_4_por_3.flatten()
print(array_unidimensional)

AttributeError: module 'numpy' has no attribute 'arrange'