--Importação de Bibliotecas: --

In [23]:
import pandas as pd
import numpy as np

Criação de um Array a partir de uma lista:

In [12]:
lista1=[1,2,3,4,5,6]
array1=np.array(lista1)
print(array1)

[1 2 3 4 5 6]


Principais Funções:

In [3]:
print (array1.dtype)

int64


In [8]:
print(array1.shape)

(5,)


In [5]:
aleatorio=np.random.rand(2,3)
print(aleatorio)

[[0.86436459 0.48467313 0.32252812]
 [0.5648192  0.23908604 0.36840084]]


Funções para Manipulação de Arrays Existentes:

In [20]:
array2=array1.reshape((3,2))
print(array2)
                      

[[1 2]
 [3 4]
 [5 6]]


In [21]:
quebra=np.split(array2,3)
print(quebra)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [22]:
array3=np.array([1,2])

In [28]:
serie1=pd.Series([10,20,30],index=['a','b','c'])
print(serie1)

a    10
b    20
c    30
dtype: int64


Seleção de Índice:

In [29]:
print(serie1['a'])
print(serie1[['a','c']])

10
a    10
c    30
dtype: int64


Operações de Filtragem e Aritméticas

In [31]:
filtro1=serie1[serie1>15]
print(filtro1)

b    20
c    30
dtype: int64


In [33]:
filtro1=serie1[serie1>15]
print(filtro1)
print('-------')
serie2=serie1*3
print(serie2)

b    20
c    30
dtype: int64
-------
a    30
b    60
c    90
dtype: int64


In [38]:
serie3=pd.Series([1,2,3,4])
serie4=pd.Series([5,6,7,8])

#Operações Fundamentais
print(serie3+serie4)
print("------")
print(serie3-serie4)
print("------")
print(serie3*serie4)
print("------")
print(serie3/serie4)

0     6
1     8
2    10
3    12
dtype: int64
------
0   -4
1   -4
2   -4
3   -4
dtype: int64
------
0     5
1    12
2    21
3    32
dtype: int64
------
0    0.200000
1    0.333333
2    0.428571
3    0.500000
dtype: float64


In [40]:
#Suporte a Valores Nulos:

serievazia=pd.Series([10,np.nan,30])
print(serievazia) #NaN = "null as Number"

0    10.0
1     NaN
2    30.0
dtype: float64


In [41]:
print(serie3+serievazia)
print("------")
print(serie3-serievazia)
print("------")
print(serie3*serievazia)
print("------")
print(serie3/serievazia)

0    11.0
1     NaN
2    33.0
3     NaN
dtype: float64
------
0    -9.0
1     NaN
2   -27.0
3     NaN
dtype: float64
------
0    10.0
1     NaN
2    90.0
3     NaN
dtype: float64
------
0    0.1
1    NaN
2    0.1
3    NaN
dtype: float64
